#!/usr/bin/env bash

# Compresses a PDF out to one of the standards specified by ghostscript.
#
# These standards are documented in the ghostscript docs
# https://superuser.com/a/435558
# https://ghostscript.com/docs/9.54.0/VectorDevices.htm
#
# Requires the gs command, which can be acquired on Ubuntu/Debian
# via `sudo apt-get install ghostscript`

usage() { echo "Usage: $0 [-s <screen|ebook|prepress|default>] -o output_file input_files+" 1>&2; exit 1; }

while getopts ":s:o:" opt; do
    case "${opt}" in
        s)
            s=${OPTARG}
            case "${s}" in
                screen|ebook|prepress|default) ;;
                *) usage;;
            esac
            ;;
        o)
            o="${OPTARG}"
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${s}" ]; then
    s="default"
fi

if [ -z "${o}" ]; then
    usage;
fi

gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/${s} -dNOPAUSE -dQUIET -dBATCH -sOutputFile="${o}" ${@}
